// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eShop.Infrastructure;

#nullable disable

namespace eShop.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230716101437_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("eShop.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("name");

                    b.Property<double?>("PriceAmount")
                        .IsRequired()
                        .HasPrecision(8)
                        .HasColumnType("double")
                        .HasColumnName("price_amount");

                    b.Property<int>("PriceCurrency")
                        .HasColumnType("int")
                        .HasColumnName("price_currency");

                    b.Property<int?>("Sku")
                        .IsRequired()
                        .HasPrecision(3)
                        .HasColumnType("int")
                        .HasColumnName("sku");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.ToTable("products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
